// Progressive enhancement only. index.html's film cards are static HTML
// (generated by scripts/build_static.py from data/films.json) so crawlers
// and no-JS clients see real content -- this file just wires up behavior
// on top of markup that already exists, and never fetches or rebuilds it.

// Only one film's audio plays at a time -- unmuting a clip mutes every
// other clip. Narration is different: most of these are silent films with
// just an orchestral score, so the narrator can read right over that score
// like a documentary voiceover. Listen ducks its own card's clip to a low
// volume instead of silencing it, and only cancels a narration running on
// a *different* card (still only one voice at a time).
function muteOtherVideos(exceptVideo) {
  document.querySelectorAll("video").forEach((v) => {
    if (v !== exceptVideo) v.muted = true;
  });
}

// Only one narration plays at a time, whether it's a pre-generated voice
// clip or the browser-TTS fallback. Whichever card started narrating last
// registers its own stop function here; starting a new one calls it first.
let activeStopNarration = null;

const CLIP_DUCK_VOLUME = 0.4;

// The reaction-cam's expression follows whichever card you're hovering.
function moodForGenre(genre) {
  const g = genre.toLowerCase();
  if (g.includes("horror") || g.includes("psychological")) return "scared";
  if (g.includes("comedy")) return "laughing";
  if (g.includes("science")) return "amazed";
  return "neutral";
}

function setReactionMood(mood) {
  const cam = document.querySelector(".reaction-cam");
  if (cam) cam.dataset.mood = mood;
}

const speechSupported = "speechSynthesis" in window;

function enhanceCard(card) {
  const video = card.querySelector(".clip-video");
  const soundBadge = card.querySelector(".sound-badge");
  const narrateBtn = card.querySelector(".narrate-btn");
  const narrationAudio = card.querySelector(".narration-audio");
  const commentary = card.querySelector(".commentary");
  const mood = moodForGenre(card.dataset.genre || "");

  card.addEventListener("mouseenter", () => {
    video.play().catch(() => {});
    setReactionMood(mood);
  });
  card.addEventListener("mouseleave", () => {
    const ownNarrationPlaying = narrateBtn.classList.contains("narrating");
    if (!ownNarrationPlaying) video.pause();
    setReactionMood("neutral");
  });

  const syncSoundBadge = () => {
    soundBadge.textContent = video.muted ? "🔇" : "🔊";
    soundBadge.setAttribute("aria-label", video.muted ? "Play clip with sound" : "Mute clip");
  };
  syncSoundBadge();
  video.addEventListener("volumechange", syncSoundBadge);

  const toggleSound = (event) => {
    event.stopPropagation();
    if (video.muted) {
      const ownNarrationPlaying = narrateBtn.classList.contains("narrating");
      if (!ownNarrationPlaying && activeStopNarration) activeStopNarration();
      muteOtherVideos(video);
      video.muted = false;
      video.volume = ownNarrationPlaying ? CLIP_DUCK_VOLUME : 1;
      video.play().catch(() => {});
    } else {
      video.muted = true;
    }
  };
  video.addEventListener("click", toggleSound);
  soundBadge.addEventListener("click", toggleSound);

  const stopThisNarration = () => {
    narrationAudio.pause();
    narrationAudio.currentTime = 0;
    window.speechSynthesis.cancel();
    narrateBtn.classList.remove("narrating");
    narrateBtn.textContent = "🔊 Listen";
    video.volume = 1;
    if (activeStopNarration === stopThisNarration) activeStopNarration = null;
  };

  const speakFallback = () => {
    if (!speechSupported) {
      stopThisNarration();
      return;
    }
    const utterance = new SpeechSynthesisUtterance(commentary.textContent);
    utterance.rate = 0.95;
    utterance.onend = utterance.onerror = stopThisNarration;
    window.speechSynthesis.speak(utterance);
  };

  narrateBtn.addEventListener("click", () => {
    if (narrateBtn.classList.contains("narrating")) {
      stopThisNarration();
      return;
    }

    if (activeStopNarration) activeStopNarration(); // only one narration at a time
    muteOtherVideos(video); // ...and only one film's audio at a time
    video.muted = false;
    video.volume = CLIP_DUCK_VOLUME; // ducked so the narrator reads clearly over the score
    video.play().catch(() => {});

    narrateBtn.classList.add("narrating");
    narrateBtn.textContent = "⏸ Reading…";
    activeStopNarration = stopThisNarration;

    narrationAudio.currentTime = 0;
    narrationAudio.onended = stopThisNarration;
    narrationAudio.onerror = speakFallback;
    narrationAudio.play().catch(speakFallback);
  });
}

document.querySelectorAll(".card").forEach(enhanceCard);
